spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  database: h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      server:
        port:8080
